project_id = "qtrubtfubdzodahsfacv"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-transactional-email]
    verify_jwt = true
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.handle-email-unsubscribe]
    verify_jwt = false
  [functions.handle-email-suppression]
    verify_jwt = false
  [functions.mpesa-validation]
    verify_jwt = false
  [functions.mpesa-confirmation]
    verify_jwt = false
  [functions.mpesa-b2c-result]
    verify_jwt = false
  [functions.mpesa-b2c-timeout]
    verify_jwt = false
  [functions.mpesa-b2c-request]
    verify_jwt = true
  [functions.mpesa-register-urls]
    verify_jwt = true
  [functions.mpesa-reversal]
    verify_jwt = true
  [functions.mpesa-status-query]
    verify_jwt = true
  [functions.payment-validation]
    verify_jwt = false
  [functions.payment-confirmation]
    verify_jwt = false
